server {
  # Escuchar en el puerto 8080, como se define en el 'docker run'
  listen 8080;

  # server_name localhost; (Es opcional, se puede quitar)

  # Directorio raíz donde están los archivos de Angular
  root /usr/share/nginx/html;
  index index.html;

  # Configuración clave para la SPA de Angular
  location / {
    try_files $uri $uri/ /index.html;
  }
}