spring.application.name=sales-ms

server.port=8080

spring.r2dbc.url=r2dbc:postgresql://grupo-4.cbicg8gw8cw4.us-east-2.rds.amazonaws.com:5432/postgres?schema=salesdb&sslMode=require
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:schema.sql

external.order-service-base-url=http://ec2-18-191-30-136.us-east-2.compute.amazonaws.com:8083/api

external.webclient.connect-timeout-ms=5000
external.webclient.read-timeout-ms=5000